### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by guodan** [petrbroz/svf-utils#64]
Hi,
I don't know what is the purpose of [forge-convert-sqlite](https://github.com/petrbroz/forge-convert-sqlite). So I didn't checkout that. Maybe is the reason of the error.

![image](https://user-images.githubusercontent.com/18362550/190098535-65b1b07c-9cae-45b4-ab1d-7f41f879585d.png)

Can anybody tell me how to config this?

**Comment by petrbroz** [comment]
Hi @guodan,

[forge-convert-sqlite](https://github.com/petrbroz/forge-convert-sqlite) is a separate research project that's trying to store/load glTF manifest to/from a sqlite database.

Regarding the error you're seeing: it looks like the converter is unable to find the file that contains list of all "fragments" (these represent individual objects in the SVF, their ID, transformation matrix, geometry, etc.). The _FragmentList.pack_ file should always be available, and it should typically sit next to the _.svf_ file.

How exactly did you download the SVF assets?

**Comment by petrbroz** [comment]
Closing this issue since no additional feedback was provided.
