### ISSUE TITLE
getManifest Request failed with status : 400 and statusText : Bad Request

### ISSUE THREAD

**Issue by HongGers** [petrbroz/svf-utils#81]
Hi! I'm trying to convert one of the svf file on my APS bucket to gltf.

#### Steps Taken
- Install `svf-utils` library :
`npm i svf-utils -g`

- obtain 2 legged token via Postman and set them as environment variable :
`set APS_ACCESS_TOKEN=<my_token>`

- run :
`svf-to-gltf <my_urn>`

it should convert the provided urn to gltf and place it to the path I execute this command.

#### Error Message
```
info: 15-05-2024 16:26:39:      Initializing resiliency config:  ResiliencyConfiguration (TimeOutValue: 15000) RetryCount: 5) (BackoffInterval: 10)  (CircuitBreakerInterval: 60000)
info: 15-05-2024 16:26:39:      Entered into getManifest
error: 15-05-2024 16:26:40:     getManifest Request failed with status : 400 and statusText : Bad Request and error message: undefined
ModelDerivativeApiError: getManifest Request failed with status : 400 and error message: undefined
...
```

#### Testing Environment
- OS
    - Parallels Windows 11 VM
    - Native Windows 11
- `svf-utils` version : 5.0.3 

I've used this library to generate gltf few months ago. the approach is the same but I can't made it work now. Am I doing something wrong?

**Comment by arkkuba** [comment]
Hello. Getting the same error. Is there any workaround?

**Comment by petrbroz** [comment]
Hi guys, there's a discussion in https://github.com/petrbroz/svf-utils/issues/84 that seems to be related to the issues you're experiencing. Could you please share your feedback there?
